name: Deploy Production

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Deploy to Fly
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v3

      # Setup flyctl for deployment
      - uses: superfly/flyctl-actions/setup-flyctl@master

      # Deploy backend to Fly.io
      - name: Deploy to Fly
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
